// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkbnbvtbkgozzxqekoxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrYm5idnRia2dvenp4cWVrb3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDM0NTIsImV4cCI6MjA2Mzc3OTQ1Mn0.xnhsg-_UTPbp-OLuG6GCd11UJYQ-KOHnHDWuNoybPG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);